version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: symfony-php-footAPI
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://symfony:password@db:3306/symfony?serverVersion=10.11&charset=utf8mb4"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx-footAPI
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:10.11
    container_name: symfony-db-footAPI
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
